server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka3
          uri: https://github.com/caceres1992/DemoMicroservicios
          search-paths: config-data
  application:
    name: config-service